import Navbar from "@/components/Navbar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

    // Enhanced: Render stars as React elements instead of DOM manipulation
    const renderStars = () => {
      return Array.from({ length: 300 }).map((_, i) => {
        const duration = 0.5 + Math.random() * 1.5; // random duration between 1.5s and 4s
        const delay = Math.random() * 2; // random delay between 0s and 2s
        return (
          <div
            key={i}
            className="absolute bg-white rounded-full  animate-pulse"
            style={{
              top: `${Math.random() * 100}vh`,
              left: `${Math.random() * 100}vw`,
              width: `${Math.random() * 2 + 2}px`,
              height: `${Math.random() * 2 + 2}px`,
              animationDuration: `${duration}s`,
              animationDelay: `${delay}s`,
            }}
          />
        );
      });
    };
  return (
    <html lang="en">
      <body>
        {children}
        <div className="fixed w-screen h-screen top-0 left-0 pointer-events-none -z-10">
              {renderStars()}
            </div>
      </body>
    </html>
  );
}
